// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfmkhtlulsfmohoeprkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmbWtodGx1bHNmbW9ob2VwcmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzY5OTMsImV4cCI6MjA1NzYxMjk5M30.9MTTc_WP4uvt4AePh3RzoXBkt9tYZMCAEz6mHEL8eUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);